services:
  frontend:
    build:
      context: ./app  # Path to your Vite React app
      dockerfile: dev.Dockerfile
    volumes:
      - ./app:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5005:5005"
    command: ["npm", "run", "dev", "--", "--host"]

  backend:
    build:
      context: ./server  # Path to your Go server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  nginx:
    image: nginx:alpine
    ports:
      - "5000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend