services:
  frontend:
    build:
      context: .
      dockerfile: build/app/dev/Dockerfile
    volumes:
      - ./app:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5005:5005"

  backend:
    build:
      context: .
      dockerfile: build/server/Dockerfile
    ports:
      - "8080:8080"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"

  nginx:
    image: nginx:alpine
    ports:
      - "5000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro