services:
  llm:
    build:
      context: .
      dockerfile: build/llm/Dockerfile
    environment:
      - MODEL_PATH=/app/models/SAINEMO-reMIX.i1-Q6_K.gguf
    volumes:
      - /home/sol/programming/ai/models:/app/models