services:
  llmq-app:
    build:
      context: .
      dockerfile: dev.Dockerfile  # Specify your custom Dockerfile name here
    ports:
      - "5005:5005"
    volumes:
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "dev", "--", "--host"]
