// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: proto/dbee.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Dbee_SayHello_FullMethodName = "/proto.Dbee/SayHello"
)

// DbeeClient is the client API for Dbee service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The Dbee service definition.
type DbeeClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type dbeeClient struct {
	cc grpc.ClientConnInterface
}

func NewDbeeClient(cc grpc.ClientConnInterface) DbeeClient {
	return &dbeeClient{cc}
}

func (c *dbeeClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, Dbee_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DbeeServer is the server API for Dbee service.
// All implementations must embed UnimplementedDbeeServer
// for forward compatibility.
//
// The Dbee service definition.
type DbeeServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedDbeeServer()
}

// UnimplementedDbeeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDbeeServer struct{}

func (UnimplementedDbeeServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedDbeeServer) mustEmbedUnimplementedDbeeServer() {}
func (UnimplementedDbeeServer) testEmbeddedByValue()              {}

// UnsafeDbeeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DbeeServer will
// result in compilation errors.
type UnsafeDbeeServer interface {
	mustEmbedUnimplementedDbeeServer()
}

func RegisterDbeeServer(s grpc.ServiceRegistrar, srv DbeeServer) {
	// If the following call pancis, it indicates UnimplementedDbeeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Dbee_ServiceDesc, srv)
}

func _Dbee_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbeeServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dbee_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbeeServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Dbee_ServiceDesc is the grpc.ServiceDesc for Dbee service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Dbee_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Dbee",
	HandlerType: (*DbeeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Dbee_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dbee.proto",
}
